title: hawkes.info
description: hawkes.info
# logo: /assets/img/logo.png
show_downloads: false
google_analytics:

theme: minima

minima:
  skin: dark

header_pages:
  - index.md

permalink: /:slug/

plugins:
  - jekyll-redirect-from

# repository: mh0w/mh0w.github.io
